<a href="https://colab.research.google.com/github/anggardhanoano/ML-Project/blob/master/bangkit_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [87]:
url = 'https://github.com/haysacks/midi-generator/raw/master/jazz-midi.csv'
df = pd.read_csv(url, index_col = 0)
print(df.shape)
df.head()

(818, 5)


Name  ... len_Uni_Notes
0      BreezeAndI.mid  ...            27
1       IfIHadYou.mid  ...            37
2  IllBeSeeingYou.mid  ...            29
3       JustAGame.mid  ...            39
4   Unforgettable.mid  ...            28

[5 rows x 5 columns]

In [88]:
# before cleaning dataset column Notes
print(df["Notes"])

0      ['E-2', 'B-2', 'B-2', 'E-3', 'B-2', 'B-2', 'E-...
1      ['10.2.5', '10.2.5', '2.5.8', '2.5.8', '0.3.7'...
2      ['E-2', 'E-2', 'B-2', 'B-2', 'G2', 'D3', 'F2',...
3      ['B3', '6.11', 'B1', 'E4', 'B1', 'F#4', 'B1', ...
4      ['G2', 'G1', 'G2', 'G1', 'G2', 'G2', 'G2', 'C#...
                             ...                        
937    ['B-1', 'B-1', 'B-1', 'B-1', 'B-1', 'B-1', 'B-...
939    ['C2', 'C2', 'A1', 'G1', 'C2', 'C2', 'G1', 'F1...
940    ['D3', '2.5.9', '2.5.9', 'E-3', '3.7.10', '3.7...
941    ['F#4', 'A4', 'C#5', 'A4', 'A4', 'A4', 'F#4', ...
942    ['A5', '0.5', 'F5', 'B-4', 'A4', 'B-4', 'F5', ...
Name: Notes, Length: 818, dtype: object


# Data Preparation

In [89]:
# Cleaning and use just first 100 data from dataset column Notes
notes = df["Notes"][0:100].str.replace("'", "").str.replace(' ', '').str.replace('{', '').str.replace('}', '').str.strip('[]').str.split(',')
print(notes)

0      [E-2, B-2, B-2, E-3, B-2, B-2, E-2, B-2, E-2, ...
1      [10.2.5, 10.2.5, 2.5.8, 2.5.8, 0.3.7, 0.3.7, 1...
2      [E-2, E-2, B-2, B-2, G2, D3, F2, F2, C3, C2, F...
3      [B3, 6.11, B1, E4, B1, F#4, B1, G4, 2.7, G1, A...
4      [G2, G1, G2, G1, G2, G2, G2, C#3, G2, G1, C#3,...
                             ...                        
107    [E2, 7.11.2, 9.1.4, B2, D3, B2, 1.7, 2.8, E3, ...
108    [9.1, 9, E3, 9.1, 2.4.9, 2.4.9, 9, E3, 9.1, 9,...
110    [B2, 2.6, B3, F#3, B3, F#3, C#4, F#3, D4, F#3,...
111    [B4, C5, D5, C5, A4, A4, G4, A4, B-4, B-4, B-4...
112    [0.5, 0.5, G#3, 7.10, E-4, E-2, B-2, E-3, E-4,...
Name: Notes, Length: 100, dtype: object


In [90]:
# Convert the multidimensional list into 1D list to elimininate duplicate value
notes = [j for i in list(notes) for j in i]
print(notes)

['E-2', 'B-2', 'B-2', 'E-3', 'B-2', 'B-2', 'E-2', 'B-2', 'E-2', 'B-2', 'E-1', 'E-2', 'B-2', 'B-2', 'E-3', 'E-3', 'B-2', 'G2', 'E-2', 'E2', 'B2', 'B2', 'E3', 'B2', 'B2', 'E-2', 'E-2', 'B-2', 'B-2', 'E-2', 'E-1', 'E-2', 'B-1', 'F2', 'E-2', 'B-2', 'E-3', 'B-2', 'E-2', 'E-1', 'B-2', 'E-1', 'E-3', 'E-2', 'B-2', 'F2', 'E2', 'B1', 'B1', 'E2', 'E1', 'B1', 'E-2', 'B-2', 'E2', 'E-2', 'C2', 'F2', 'C3', 'F3', 'C3', 'F#2', 'B-1', 'B-1', 'G2', 'G#2', 'C3', 'G2', 'G1', 'A2', 'B-2', 'D3', 'G2', 'C2', 'D2', 'E-2', 'G2', 'F#2', 'F2', 'F1', 'G2', 'G#2', 'C3', 'F2', 'B-1', 'B-2', 'F2', 'D2', 'E-2', 'E-3', 'B-2', 'G2', 'C2', 'D2', 'E2', 'G2', 'F2', 'F2', 'G2', 'G#2', 'C3', 'B-1', 'C3', 'B-1', 'B-1', 'B-1', 'B-1', 'E-2', 'B-2', 'E-3', 'B-2', 'E2', 'E-2', 'E-2', 'B-2', 'C2', 'C2', 'F2', 'C2', 'G2', 'G#2', 'C2', 'C3', 'C2', 'B-1', 'B-1', 'C2', 'D2', 'F2', 'E-2', 'E-3', 'B-2', 'G2', 'F2', 'A1', 'B-1', 'E2', 'E-2', 'F2', 'G2', 'B-2', 'B-1', 'B-1', 'B-1', 'B-1', 'E-2', 'B-2', 'E-2', 'B-2', 'E-1', 'E-2', 'E-1', '

In [91]:
# sort and eliminate duplicate notes, then got all pitch names
pitchnames = sorted(set(i for i in notes))
print(pitchnames)

['0', '0.1', '0.1.2', '0.1.3', '0.1.3.7', '0.1.4', '0.1.5', '0.1.5.8', '0.2', '0.2.3', '0.2.3.7', '0.2.4', '0.2.4.5', '0.2.4.5.7', '0.2.4.5.7.9', '0.2.4.6', '0.2.4.7', '0.2.4.7.9', '0.2.5', '0.2.5.7', '0.2.5.8', '0.2.6', '0.2.7', '0.3', '0.3.4', '0.3.4.7', '0.3.5', '0.3.5.6', '0.3.5.6.8', '0.3.5.7.8', '0.3.5.8', '0.3.6', '0.3.6.7', '0.3.6.8', '0.3.6.9', '0.3.7', '0.4', '0.4.5', '0.4.5.7', '0.4.6', '0.4.7', '0.4.8', '0.5', '0.5.6', '0.6', '1', '1.2', '1.2.4.7', '1.2.5.8', '1.2.6', '1.2.6.9', '1.3', '1.3.4', '1.3.5', '1.3.5.8', '1.3.5.9', '1.3.6', '1.3.6.9', '1.3.7', '1.3.7.9', '1.3.8', '1.4', '1.4.6.9', '1.4.7', '1.4.7.10', '1.4.7.9', '1.4.8', '1.5', '1.5.6', '1.5.6.8', '1.5.7', '1.5.8', '1.5.9', '1.6', '1.6.7', '1.7', '10', '10.0', '10.0.1', '10.0.1.3.4', '10.0.1.5', '10.0.2', '10.0.2.4', '10.0.2.4.7', '10.0.2.5', '10.0.3', '10.0.3.5', '10.0.3.6', '10.0.4', '10.0.5', '10.1', '10.1.2.3.4.5', '10.1.3', '10.1.3.5', '10.1.3.5.6', '10.1.3.6', '10.1.4', '10.1.4.6', '10.1.4.6.7', '10.1.5', '1

In [92]:
# categories for all pitchnames, mapped from pitchnames list
notes_categories = dict((note,number) for number, note in enumerate(pitchnames))
print(notes_categories)

{'0': 0, '0.1': 1, '0.1.2': 2, '0.1.3': 3, '0.1.3.7': 4, '0.1.4': 5, '0.1.5': 6, '0.1.5.8': 7, '0.2': 8, '0.2.3': 9, '0.2.3.7': 10, '0.2.4': 11, '0.2.4.5': 12, '0.2.4.5.7': 13, '0.2.4.5.7.9': 14, '0.2.4.6': 15, '0.2.4.7': 16, '0.2.4.7.9': 17, '0.2.5': 18, '0.2.5.7': 19, '0.2.5.8': 20, '0.2.6': 21, '0.2.7': 22, '0.3': 23, '0.3.4': 24, '0.3.4.7': 25, '0.3.5': 26, '0.3.5.6': 27, '0.3.5.6.8': 28, '0.3.5.7.8': 29, '0.3.5.8': 30, '0.3.6': 31, '0.3.6.7': 32, '0.3.6.8': 33, '0.3.6.9': 34, '0.3.7': 35, '0.4': 36, '0.4.5': 37, '0.4.5.7': 38, '0.4.6': 39, '0.4.7': 40, '0.4.8': 41, '0.5': 42, '0.5.6': 43, '0.6': 44, '1': 45, '1.2': 46, '1.2.4.7': 47, '1.2.5.8': 48, '1.2.6': 49, '1.2.6.9': 50, '1.3': 51, '1.3.4': 52, '1.3.5': 53, '1.3.5.8': 54, '1.3.5.9': 55, '1.3.6': 56, '1.3.6.9': 57, '1.3.7': 58, '1.3.7.9': 59, '1.3.8': 60, '1.4': 61, '1.4.6.9': 62, '1.4.7': 63, '1.4.7.10': 64, '1.4.7.9': 65, '1.4.8': 66, '1.5': 67, '1.5.6': 68, '1.5.6.8': 69, '1.5.7': 70, '1.5.8': 71, '1.5.9': 72, '1.6': 73, '1

In [0]:
# sequence for predict 1 note of notes sequence
sequence_length = 50
length = len(notes) - sequence_length

# Input and output for LSTM
x = []
y = []

for i in range(length):
    sequence_in = notes[i : i + sequence_length]
    sequence_out = notes[i + sequence_length]
    
    x.append([notes_categories[note] for note in sequence_in])
    y.append(notes_categories[sequence_out])


n_patterns = len(x)

n_vocab = len(set(notes))


In [94]:
# reshape x to become 1 dimension
x = np.reshape(x, (n_patterns, sequence_length, 1))
print(x[0])

[[468]
 [430]
 [430]
 [469]
 [430]
 [430]
 [468]
 [430]
 [468]
 [430]
 [467]
 [468]
 [430]
 [430]
 [469]
 [469]
 [430]
 [509]
 [468]
 [475]
 [438]
 [438]
 [476]
 [438]
 [438]
 [468]
 [468]
 [430]
 [430]
 [468]
 [467]
 [468]
 [429]
 [492]
 [468]
 [430]
 [469]
 [430]
 [468]
 [467]
 [430]
 [467]
 [469]
 [468]
 [430]
 [492]
 [475]
 [437]
 [437]
 [475]]


In [95]:
# Normalise x into 0 - 1 value
x = x / float(n_vocab)
print(x[0])


[[0.90873786]
 [0.83495146]
 [0.83495146]
 [0.91067961]
 [0.83495146]
 [0.83495146]
 [0.90873786]
 [0.83495146]
 [0.90873786]
 [0.83495146]
 [0.90679612]
 [0.90873786]
 [0.83495146]
 [0.83495146]
 [0.91067961]
 [0.91067961]
 [0.83495146]
 [0.98834951]
 [0.90873786]
 [0.9223301 ]
 [0.85048544]
 [0.85048544]
 [0.92427184]
 [0.85048544]
 [0.85048544]
 [0.90873786]
 [0.90873786]
 [0.83495146]
 [0.83495146]
 [0.90873786]
 [0.90679612]
 [0.90873786]
 [0.83300971]
 [0.95533981]
 [0.90873786]
 [0.83495146]
 [0.91067961]
 [0.83495146]
 [0.90873786]
 [0.90679612]
 [0.83495146]
 [0.90679612]
 [0.91067961]
 [0.90873786]
 [0.83495146]
 [0.95533981]
 [0.9223301 ]
 [0.84854369]
 [0.84854369]
 [0.9223301 ]]


In [96]:
# Encoding categorical Output + one hot encode categorical

# Before OneHotEncode and reshape
y = np.array(y)
hot_encode = OneHotEncoder(sparse=False)
print(y)

[474 437 468 ... 493 503 457]


In [97]:
# After OnehotEncode and reshape
y = y.reshape(len(y), 1)
y = hot_encode.fit_transform(y)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
# preparation complete when data splitted to training dataset and test dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)